trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt install libgtk-3-dev libpcre2-dev libvte-2.91-dev
  displayName: Install prerequisites

- task: CMake@1
  displayName: Run CMake build
