trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- script: |
    sudo apt update -y
    sudo apt install -y libgtk-3-dev libpcre2-dev libvte-2.91-dev
  displayName: Install prerequisites

- task: CMake@1
  inputs:
    workingDirectory: 'build'
    cmakeArgs: '-DCMAKE_BUILD_TYPE=Debug ..'
  displayName: Generate project

- script: |
    cd build
    make
  displayName: Build project
  
